rebalancer/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import equity.views

urlpatterns = [

    url(r'^admin/', include(admin.site.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^$', equity.views.home, name='home'),
    url(r'^index/', equity.views.index, name='index'),

    # url(r'^selectModelAccounts/', 'equity.views.selectModelAccounts', name='selectModelAccounts'),

    url(r'^newRebalance/', equity.views.newRebalance, name='newRebalance'),
    url(r'^accountSelections/', equity.views.accountSelections, name='accountSelections'),

    url(r'^accounts/', equity.views.accounts, name='accounts'),
    url(r'^accounts/filter/(?P<id>\d+)/$', equity.views.accountsByFilter, name='accountsByFilter'),
    url(r'^filter/$', equity.views.accountsByFilter, name='accountsByFilter'),

    url(r'^referenceData/', equity.views.referenceData, name='referenceData'),
    url(r'^securities/', equity.views.securities, name='securities'),
    url(r'^rulesCreation/', equity.views.rulesCreation, name='rulesCreation'),
    # url(r'^models/([0-9]+)/$', 'equity.views.updateModelWithTargetWeights', name='models'),

    url(r'^uploadModels/', equity.views.upload, name='file_upload'),
    # You may optionally define a delete url as well
    url(r'^delete/(?P<pk>\d+)$', equity.views.upload_delete, name='file_delete'),

    url(r'^createModelName/$', equity.views.Create_Model_Name, name='createModelName'),

    url(r'^accountParameters/$', equity.views.accountParameters, name='accountParameters'),
    url(r'^accountSearchFilter/$', equity.views.accountSearchFilter, name='accountSearchFilter'),
    url(r'^modelParameters/$', equity.views.modelParameters, name='modelParameters'),
    url(r'^Account/SaveAccount/$', equity.views.save_account_list, name='save_account_list'),
    url(r'^GetAllAccount/$', equity.views.get_account_list, name='get_account_list'),

    url(r'^getClassifications/$', equity.views.getClassifications, name='getClassifications'),
    url(r'^getSavedClassificationModel/(?P<id>\w+)', equity.views.getSavedClassificationModel,
        name='getSavedClassificationModel'),

    url(r'^saveClassifications/$', equity.views.saveClassifications, name='saveClassifications'),
    url(r'^updateSecuritySelectionModels/$', equity.views.updateSecuritySelectionModels,
        name='updateSecuritySelectionModels'),

    url(r'^deleteSecuritySelectionModels/$', equity.views.deleteModel, name='deleteModel'),
    url(r'^deleteSecuritySelectionModels/(?P<id>\w+)/$', equity.views.deleteSecuritySelectionModels,
        name='deleteSecuritySelectionModels'),

    url(r'^updateModelWithSecurity/(?P<id>\w+)/$', equity.views.updateModelWithSecurity,
        name='updateModelWithSecurity'),
    url(r'^updateModelWithTargetWeights/$', equity.views.updateModelWithTargetWeights,
        name='updateModelWithTargetWeights'),
    url(r'^updateModelNodes/$', equity.views.updateModelNodes, name='updateModelNodes'),
    url(r'^uploadSecuritySelectionModels/', equity.views.uploadSecuritySelectionModels,
        name='uploadSecuritySelectionModels'),

    url(r'^getSSMList/$', equity.views.get_SSMList, name='get_SSMList'),

    url(r'^createModelWeights/$', equity.views.createModelWeights, name='createModelWeights'),

    url(r'^getModelTargetWeights/$', equity.views.getModelTargetWeights, name='getModelTargetWeights'),

    url(r'^createSecuritySelectionModels/$', equity.views.createSecuritySelectionModels,
        name='createSecuritySelectionModels'),

    # Registration
    url(r'^Accounts/', include('registration.backends.default.urls')),

    # System Administration
    url(r'^systemFeeds/$', equity.views.systemFeeds, name='systemFeeds'),
    url(r'^editSystemFeeds/$', equity.views.systemFeeds, name='editSystemFeeds'),

]

equity/models.py
from django.db import models
from django.contrib.auth.models import User
from treebeard.al_tree import AL_Node
from equity.validators import validate_tgtWeights


# Create your models here.
class Account(models.Model):
    acctCd = models.CharField(max_length=200, blank=False, default='ABC', primary_key=True, unique=True)
    shortName = models.CharField(max_length=50, blank=False, default='ABC')
    cashSegregated = models.FloatField()
    cashUnSegregated = models.FloatField()
    totCash = models.FloatField()

    def __str__(self):
        return self.shortName

    class Meta:
        ordering = ('shortName',)


class AccountManager(models.Manager):
    def get_by_natural_key(self, acctFilterName):
        return self.get(acctFilterName=acctFilterName)


class AccountFilters(models.Model):
    objects = AccountManager()

    acctFilterName = models.CharField(max_length=200)
    accountName = models.ManyToManyField(Account)
    created_by = models.ForeignKey(User, related_name='%(class)s_requests_created', default='1')
    edited_by = models.ForeignKey(User, related_name='%(class)s_requests_edited', default='1')
    createDate = models.DateTimeField(auto_now_add=True)
    updateDate = models.DateTimeField(auto_now=True)

    def natural_key(self):
        return (self.acctFilterName)

    def __unicode__(self):
        return self.acctFilterName


class NewRebalance(models.Model):
    type = models.TextField()
    name = models.CharField(max_length=200, blank=False, default='')
    action = models.TextField()
    adjustCash = models.BooleanField(default=False)
    adjustWeightDuringRebal = models.BooleanField(default=False)
    excludePendingTrades = models.BooleanField(default=False)
    reviewSwapSale = models.BooleanField(default=False)
    adjustCashDuringRebal = models.BooleanField(default=False)
    createDate = models.DateTimeField(auto_now_add=True)
    updateDate = models.DateTimeField(auto_now=True)
    FIFO = 'FIFO'
    LIFO = 'LIFO'
    AVGCOST = 'AVGCOST'

    taxLotAlgoChoices = (
        (FIFO, 'FIFO'),
        (LIFO, 'LIFO'),
        (AVGCOST, 'Average Cost'),
    )

    taxLotAlgo = models.CharField(choices=taxLotAlgoChoices, default=FIFO, max_length=80)
    accounts = models.ForeignKey(Account, default='ABC')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('createDate',)


class ClassificationManager(models.Manager):
    def get_by_natural_key(self, classificationName):
        return self.get(classificationName=classificationName)


class ClassificationNames(AL_Node):
    objects = ClassificationManager()
    classificationLevel = models.IntegerField(null=True)
    classificationName = models.CharField(max_length=100, null=True)
    parent = models.ForeignKey('self', null=True, related_name='children_set', db_index=True)
    node_order_by = ['classificationName', 'desc', 'source']
    hasChildNode = models.NullBooleanField(default=False)

    def natural_key(self):
        return (self.classificationName)

    def __unicode__(self):
        return self.classificationName


class Countries(models.Model):
    cntry_cd = models.CharField(max_length=100, null=True)
    cntry_name = models.CharField(max_length=1000)
    iso_cntry_cd = models.CharField(max_length=50)

    def natural_key(self):
        return self.cntry_name

    def __unicode__(self):
        return self.cntry_name


class Currencies(models.Model):
    currencyCd = models.CharField(max_length=100, null=True)
    currencyName = models.CharField(max_length=100, null=True)
    calc_precision = models.FloatField(null=True)


class AllocationModelManager(models.Manager):
    def get_by_natural_key(self, modelName):
        return self.get(modelName=modelName)


class Exchanges(models.Model):
    exch_cd = models.CharField(max_length=200, unique=True)
    exchange = models.CharField(max_length=1000)
    cntry_cd = models.ForeignKey(Countries)
    exch_or_otc = models.CharField(max_length=5)
    iso_exch_cd = models.CharField(max_length=10)
    tz_region = models.CharField(max_length=10)
    open_time = models.TimeField(null=True)
    mid_open_time = models.TimeField(null=True)
    mid_close_time = models.TimeField(null=True)
    cutoff_time = models.TimeField(null=True)
    close_time = models.TimeField(null=True)


class AllocationModels(models.Model):
    objects = AllocationModelManager()

    # id = models.AutoField(primary_key=True)
    modelName = models.CharField(max_length=100, unique=True)
    created_by = models.ForeignKey(User, related_name='%(class)s_requests_created', default='1')
    edited_by = models.ForeignKey(User, related_name='%(class)s_requests_edited', default='1')

    def natural_key(self):
        return (self.modelName)

    class Meta:
        ordering = ['modelName']


class AllocationNodes(models.Model):
    allocationModel = models.ForeignKey(AllocationModels, related_name='allocationNodes')
    classificationName = models.ForeignKey(ClassificationNames, related_name='classificationNames')
    level = models.IntegerField()
    dependentNode = models.CharField(max_length=300, null=True)

    def natural_key(self):
        return (self.allocationModel.natural_key() + self.classificationName.natural_key())

    natural_key.dependencies = ['equity.AllocationModel', 'equity.ClassificationNames']


class SecurityType(models.Model):
    secTypCd = models.CharField(primary_key=True, max_length=100)
    secName = models.CharField(max_length=200)
    pricingMult = models.FloatField(null=True)
    contractSize = models.IntegerField(null=True)
    accrualType = models.CharField(max_length=100, null=True)
    bloombergName = models.CharField(max_length=100, null=True)



class Identity(models.Model):
    type = models.CharField(max_length=20)
    value = models.CharField(max_length=20)


class Securities(models.Model):
    AL = 'Alabama',
    AK = 'Alaska',
    AZ = 'Arizona',
    AR = 'Arkansas',
    CA = 'California',
    CO = 'Colorado',
    CT = 'Connecticut',
    DE = 'Delaware',
    FL = 'Florida',
    GA = 'Georgia',
    HI = 'Hawaii',
    ID = 'Idaho',
    IL = 'Illinois',
    IN = 'Indiana',
    IA = 'Iowa',
    KS = 'Kansas',
    KY = 'Kentucky',
    LA = 'Louisiana',
    ME = 'Maine',
    MD = 'Maryland',
    MA = 'Massachusetts',
    MI = 'Michigan',
    MN = 'Minnesota',
    MS = 'Mississippi',
    MO = 'Missouri',
    MT = 'Montana',
    NE = 'Nebraska',
    NV = 'Nevada',
    NH = 'New Hampshire',
    NJ = 'New Jersey',
    NM = 'New Mexico',
    NY = 'New York',
    NC = 'North Carolina',
    ND = 'North Dakota',
    OH = 'Ohio',
    OK = 'Oklahoma',
    OR = 'Oregon',
    PA = 'Pennsylvania',
    RI = 'Rhode Island',
    SC = 'South Carolina',
    SD = 'South Dakota',
    TN = 'Tennessee',
    TX = 'Texas',
    UT = 'Utah',
    VT = 'Vermont',
    VA = 'Virginia',
    WA = 'Washington',
    WV = 'West Virginia',
    WI = 'Wisconsin',
    WY = 'Wyoming',

    STATE_CHOICES = (
        (AL, 'Alabama'),
        (AK, 'Alaska'),
        (AZ, 'Arizona'),
        (AR, 'Arkansas'),
        (CA, 'California'),
        (CO, 'Colorado'),
        (CT, 'Connecticut'),
        (DE, 'Delaware'),
        (FL, 'Florida'),
        (GA, 'Georgia'),
        (HI, 'Hawaii'),
        (ID, 'Idaho'),
        (IL, 'Illinois'),
        (IN, 'Indiana'),
        (IA, 'Iowa'),
        (KS, 'Kansas'),
        (KY, 'Kentucky'),
        (LA, 'Louisiana'),
        (ME, 'Maine'),
        (MD, 'Maryland'),
        (MA, 'Massachusetts'),
        (MI, 'Michigan'),
        (MN, 'Minnesota'),
        (MS, 'Mississippi'),
        (MO, 'Missouri'),
        (MT, 'Montana'),
        (NE, 'Nebraska'),
        (NV, 'Nevada'),
        (NH, 'New Hampshire'),
        (NJ, 'New Jersey'),
        (NM, 'New Mexico'),
        (NY, 'New York'),
        (NC, 'North Carolina'),
        (ND, 'North Dakota'),
        (OH, 'Ohio'),
        (OK, 'Oklahoma'),
        (OR, 'Oregon'),
        (PA, 'Pennsylvania'),
        (RI, 'Rhode Island'),
        (SC, 'South Carolina'),
        (SD, 'South Dakota'),
        (TN, 'Tennessee'),
        (TX, 'Texas'),
        (UT, 'Utah'),
        (VT, 'Vermont'),
        (VA, 'Virginia'),
        (WA, 'Washington'),
        (WV, 'West Virginia'),
        (WI, 'Wisconsin'),
        (WY, 'Wyoming'),
    )
    secId = models.IntegerField(primary_key=True)
    extSecId = models.CharField(max_length=100, null=True)
    secName = models.CharField(max_length=100, blank=False, verbose_name="Securities Name")
    shortName = models.CharField(max_length=100, null=True, verbose_name="Short Name")
    secType = models.ForeignKey(SecurityType)
    issueState = models.CharField(max_length=100, choices=STATE_CHOICES, verbose_name="Issue State")
    issueCountry = models.ForeignKey(Countries, verbose_name="Issue Country")
    issueDate = models.DateField()
    locCurrencyCd = models.CharField(max_length=20)
    crossCurrencyCd = models.CharField(max_length=20)
    listExchCd = models.CharField(max_length=20, verbose_name="Exchange")
    baseCurrency = models.CharField(max_length=5, default='USD', verbose_name="Base Curr.")
    mktPrice = models.FloatField(verbose_name="Market Price")
    amtIssued = models.FloatField()
    amtOutstanding = models.FloatField()
    couponRate = models.FloatField(verbose_name="Coupon/Int. Rate")
    ticker = models.CharField(max_length=100, null=True)
    isin = models.CharField(max_length=100, null=True, verbose_name="ISIN")
    sedol = models.CharField(max_length=100, null=True)
    cusip = models.CharField(max_length=100, null=True)
    RIC = models.CharField(max_length=100, verbose_name="Reuters IC")
    valoran = models.CharField(max_length=100, null=True)
    avgLife = models.DateField
    matureDate = models.DateField
    callDate = models.DateField
    putDate = models.DateField
    nextCouponDate = models.DateField
    strikePrice = models.FloatField()
    duration = models.FloatField
    expireDate = models.DateField
    fedTaxable = models.DateField

equity/templates/AccountSearchFilter.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block nav_active_list %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'newRebalance' %}">New Rebalance</a></li>
    <li class="dropdown active">
        <a href="{% url 'accounts' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Accounts <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="#">Create Account Filter</a></li>
        </ul>
    </li>
    <li><a href="{% url 'referenceData' %}">Reference Data</a></li>
    <li><a href="{% url 'securities' %}">Securities</a></li>
    <li><a href="{% url 'createNewModel' %}">Create AAM/SSM</a></li>
    <li><a href="{% url 'rulesCreation' %}">Rules Creation</a></li>
{% endblock %}

{% block title %}New Rebalance:{% endblock %}

{% block primary %}

    <div class="page-header">
        <h1>Create an Account Filter</h1>
    </div>
    <form class="form-horizontal" action="{% url 'accountSearchFilter' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">
                    {{ account_filter_form|crispy }}
                    <input class="btn btn-primary" id="button" type="Submit" value="Save">
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block css %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href="{% static "bootstrap/css/sumoselect.css" %}" rel="stylesheet">
{% endblock %}

{% block script %}
    <script src="{% static "bootstrap/js/jquery.sumoselect.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            select = $('.selectmultiple').SumoSelect();


            var token = $('input[name="csrfmiddlewaretoken"]').prop('value');
            var selectedArray = [];
            /*
             $(".form-horizontal").submit(function(e){

             e.preventDefault();

             $('.select').each(function(){
             selectedArray.push($(this).val());
             });

             $.ajax({
             type: $(this).attr('method'),
             url: "
            {% url 'accountSearchFilter' %}",
             datatype: 'json',
             data: {
             data: $(this).serialize(),
             csrfmiddlewaretoken:token
             },

             success: function (result) {

             }
             });
             });
             */
        });
    </script>
{% endblock %}

equity/templates/NewRebalance_2.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block nav_active_list %}
   <ul class="nav navbar-nav">
            <li class=""><a href="{% url 'home' %}">Home</a></li>
            <li class="dropdown active">
                <a href="{% url 'newRebalance' %}" class="dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-haspopup="true"
                   aria-expanded="false">
                    New Rebalance <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" >
                    <li><a href="{% url 'newRebalance' %}">Create New Rebalance</a></li>
                    <li><a href="#">Select an Existing Rebalance</a></li>
                </ul>
            </li>

            <li class="dropdown">
                <a href="{% url 'accounts' %}" class="dropdown-toggle" data-toggle="dropdown" role="button"
                   aria-haspopup="true"
                   aria-expanded="false">
                    Accounts <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'accountSearchFilter' %}">Create Account Filter</a></li>
                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">
                    Reference Data<span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="">Positions</a></li>
                    <li><a href="#">Tax Lots</a></li>
                    <li><a href="{% url 'accounts' %}">Accounts</a></li>
                </ul>
            </li>
            <li><a href="{% url 'securities' %}">Securities</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">
                    Create AAM/SSM <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'createSecuritySelectionModels' %}">Create New Model</a></li>
                    <li><a href="{% url 'updateSecuritySelectionModels' %}">Update Existing Model</a></li>
                    <li><a href="{% url 'deleteModel' %}">Delete Model</a></li>
                </ul>
            </li>
            <li><a href="{% url 'rulesCreation' %}">Rules Creation</a></li>
        </ul>
{% endblock %}

{% block title %}New Rebalance:{% endblock %}

{% block primary %}

    <div class="page-header">
        <h1>Step 2: Account Selections</h1>
    </div>
    <form class="form-horizontal" action="{% url 'accountSelections' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">

                    {{ account_selection_form|crispy }}

                    <input class="btn btn-primary" id="button" type="Submit" value="Next >>">
                </div>
                <div class="col-md-4">
                    &nbsp;
                </div>
                <div class="col-md-4">
                    <div id="grid"></div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block css %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href="{% static "bootstrap/css/sumoselect.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "kendo/styles/kendo.common.min.css" %}"/>
    <link rel="stylesheet" href="{% static "kendo/styles/kendo.default.min.css" %}"/>
{% endblock %}

{% block script %}
    <script src="{% static "bootstrap/js/jquery.sumoselect.js" %}"></script>
    <script src="{% static "kendo/js/kendo.all.min.js" %}"></script>

    <script type="text/javascript">

        $(document).ready(function () {

            $("#id_excludeClassification").SumoSelect();

            var token = $('input[name="csrfmiddlewaretoken"]').prop('value');

            $("#id_acctFilterName").change(function () {
                var data = "";
                $.ajax({
                    type: "GET",
                    url: "../filter",
                    data: "id=" + $(this).val(),
                    csrfmiddlewaretoken: token,
                    success: function (response) {
                        $("#grid").kendoGrid({
                            data: response,
                            height: 550,
                            groupable: true,
                            sortable: true,
                            columns: [
                                {
                                    field: "acctCd",
                                    title: "Code"
                                }, {
                                    field: "shortName",
                                    title: "Account Name"
                                }]
                        });

                        var grid = $("#grid").data("kendoGrid");
                        dataSource = new kendo.data.DataSource({
                            data: response
                        });

                        grid.dataSource = dataSource;
                        dataSource.read();
                        grid.refresh();

                        data = response;
                        return response;
                    },
                    error: function () {
                        alert('Error occured');
                    }
                });
            });

        });
    </script>
{% endblock %}

equity/templates/NewRebalance_3.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block nav_active_list %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li class="dropdown active">
        <a href="{% url 'newRebalance' %}" class="dropdown-toggle active" data-toggle="dropdown" role="button"
           aria-haspopup="true"
           aria-expanded="false">
            New Rebalance <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'newRebalance' %}">Create New Rebalance</a></li>
            <li><a href="#">Select an Existing Rebalance</a></li>
        </ul>
    </li>

    <li class="dropdown">
        <a href="{% url 'accounts' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Accounts <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'accountSearchFilter' %}">Create Account Filter</a></li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Reference Data<span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="">Positions</a></li>
            <li><a href="#">Tax Lots</a></li>
            <li><a href="#">Accounts</a></li>
        </ul>
    </li>
    <li><a href="{% url 'securities' %}">Securities</a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
           aria-expanded="false">
            Create AAM/SSM <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a href="{% url 'createSecuritySelectionModels' %}">Create New Model</a></li>
            <li><a href="#">Update Existing Model</a></li>
            <li><a href="#">Delete Model</a></li>
        </ul>
    </li>
    <li><a href="{% url 'rulesCreation' %}">Rules Creation</a></li>
{% endblock %}

{% block title %}New Rebalance:{% endblock %}

{% block primary %}

    <div class="page-header">
        <h1>Step 3: Security Selection</h1>
    </div>
    <form class="form-horizontal" action="{% url 'accountSelections' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">

                    {{ security_selection_form|crispy }}

                    <input class="btn btn-primary" id="button" type="Submit" value="Next >>">
                </div>
                <div class="col-md-4">
                    &nbsp;
                </div>
                <div class="col-md-4">
                    <div id="grid"></div>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block css %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href="{% static "bootstrap/css/sumoselect.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static "kendo/styles/kendo.common.min.css" %}"/>
    <link rel="stylesheet" href="{% static "kendo/styles/kendo.default.min.css" %}"/>
{% endblock %}

{% block script %}
    <script src="{% static "bootstrap/js/jquery.sumoselect.js" %}"></script>
    <script src="{% static "kendo/js/kendo.all.min.js" %}"></script>

    <script type="text/javascript">

        $(document).ready(function () {

        });

    </script>
{% endblock %}

equity/templates/referenceData.html
{% extends 'base.html' %}

{% block css %}
    <link href="..{{ STATIC_URL }}/bootstrap/css/sumoselect.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block nav_active_list %}
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'newRebalance' %}">New Rebalance</a></li>
    <li><a href="{% url 'accounts' %}">Accounts</a></li>
    <li class="active"><a href="{% url 'referenceData' %}">Reference Data</a></li>
    <li><a href="{% url 'securities' %}">Securities</a></li>
    <li><a href="{% url 'newModel' %}">Create AAM/SSM</a></li>
    <li><a href="{% url 'rulesCreation' %}">Rules Creation</a></li>
{% endblock %}
{% block primary %}
    <legend>Reference data</legend>
    <fieldset>


    </fieldset>
{% endblock %}